site_name: SCLRota - Manual de Integração
theme: material
pages:
  - 'Conteúdo' : 'index.md'  
  - 'Anexos' : 'anexos.md'  
  - 'Sobre' : 'about.md'    
 

markdown_extensions: 
- meta
- toc
- tables
- smarty
- fenced_code